# Numpy Crash Course

In [1]:
import numpy as np

## Creating Arrays

In [2]:
my_list = [0,1,2,3,4]

In [3]:
arr = np.array(my_list)

In [4]:
arr
print(type(my_list))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [5]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## Operations

In [23]:
np.random.seed(101) # watch video for details
arr = np.random.randint(0,100,10)
arr

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [24]:
arr2 = np.random.randint(0,100,10)

In [25]:
arr2

array([ 4, 63, 40, 60, 92, 64,  5, 12, 93, 40])

In [26]:
arr.max()

95

In [27]:
arr.min()

9

In [28]:
arr.mean()

60.8

In [29]:
arr.argmin()

7

In [30]:
arr.argmax()

0

In [33]:
arr.reshape(5,2)

array([[95, 11],
       [81, 70],
       [63, 87],
       [75,  9],
       [77, 40]])

## Indexing

In [35]:
mat = np.arange(0,100).reshape(10,10)

In [36]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [37]:
row = 0
col = 1

In [38]:
mat[row,col]

1

In [44]:
# With Slices
mat[:,1:3]

array([[ 1,  2],
       [11, 12],
       [21, 22],
       [31, 32],
       [41, 42],
       [51, 52],
       [61, 62],
       [71, 72],
       [81, 82],
       [91, 92]])

In [43]:
mat[row,:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

# Great Job!